// Booking actions
export const GET_LAUNCHES = 'GET_LAUNCHES';
export const LAUNCHES_INIT = 'LAUNCHES_GET_FAILURE';
export const LAUNCHES_GET_SUCCESS = 'LAUNCHES_GET_SUCCESS';
export const LAUNCHES_GET_FAILURE = 'LAUNCHES_GET_FAILURE';

export const LAUNCHES_GET_FILTER = 'LAUNCHES_GET_FILTER';
export const SET_ORDER_BY = 'SET_ORDER_BY';
